packages:
  - 'backend'
  - 'frontend'
  - 'sdk'
allowBuilds:
  '@stellar/stellar-sdk': set this to true or false
  blake-hash: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  tiny-secp256k1: set this to true or false
  usb: set this to true or false
  utf-8-validate: set this to true or false
onlyBuiltDependencies:
  - '@stellar/stellar-sdk'
  - blake-hash
  - esbuild
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
